### ISSUE TITLE
Keyboard shortcuts screenshot out of date

### ISSUE THREAD

**Issue by bentsai** [kinopio-club/kinopio-help#10]
The keyboard shortcut screenshot at https://help.kinopio.club/posts/keyboard-shortcuts/ is slightly out of date.

### Current in app
![image](https://user-images.githubusercontent.com/228043/88610057-a954ee80-d053-11ea-8d9c-3cc773b046d7.png)

### Screenshot on help site
![image](https://kinopio-updates.s3.us-east-1.amazonaws.com/keyboard-shortcuts-list.png)

**Comment by pketh** [comment]
there's prob a lot more that's stale in those help articles. let's keep building up the list and it'll be easier to update them in one fell swoop
